// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReminderManager.Infrastructure.Data;

#nullable disable

namespace ReminderManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110060450_UpdateTable")]
    partial class UpdateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReminderManager.Domain.Entities.ModbusDeviceConfig", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<bool>("AutoReconnect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_reconnect");

                    b.Property<int>("ConnectionTimeoutMs")
                        .HasColumnType("int")
                        .HasColumnName("connection_timeout_ms");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<int>("ReadIntervalMs")
                        .HasColumnType("int")
                        .HasColumnName("read_interval_ms");

                    b.Property<int>("ReadTimeoutMs")
                        .HasColumnType("int")
                        .HasColumnName("read_timeout_ms");

                    b.Property<int>("ReconnectDelayMs")
                        .HasColumnType("int")
                        .HasColumnName("reconnect_delay_ms");

                    b.Property<ushort>("RegisterCount")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("register_count");

                    b.Property<byte>("SlaveId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("slave_id");

                    b.Property<ushort>("StartAddress")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("start_address");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceName")
                        .IsUnique();

                    b.ToTable("modbus_device_configs");
                });

            modelBuilder.Entity("ReminderManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("394ad5fe-9f8b-44d0-a90e-08b6f5c9fb84"),
                            Password = "$2a$11$EW83uhzbpehM/Ol7d/GiounkmVLjfzR7XOk5pSQuCpJbU6AgPndD.",
                            Username = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
