// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReminderManager.Infrastructure.Data;

#nullable disable

namespace ReminderManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110072733_AddVibartionSensorDataTable")]
    partial class AddVibartionSensorDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReminderManager.Domain.Entities.ModbusDeviceConfig", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<bool>("AutoReconnect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_reconnect");

                    b.Property<int>("ConnectionTimeoutMs")
                        .HasColumnType("int")
                        .HasColumnName("connection_timeout_ms");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<int>("ReadIntervalMs")
                        .HasColumnType("int")
                        .HasColumnName("read_interval_ms");

                    b.Property<int>("ReadTimeoutMs")
                        .HasColumnType("int")
                        .HasColumnName("read_timeout_ms");

                    b.Property<int>("ReconnectDelayMs")
                        .HasColumnType("int")
                        .HasColumnName("reconnect_delay_ms");

                    b.Property<ushort>("RegisterCount")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("register_count");

                    b.Property<byte>("SlaveId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("slave_id");

                    b.Property<ushort>("StartAddress")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("start_address");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceName")
                        .IsUnique();

                    b.ToTable("modbus_device_configs");
                });

            modelBuilder.Entity("ReminderManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b405645c-b2ec-4010-b190-f77e05041833"),
                            Password = "$2a$11$RH/JqjqdZA/flwANjCBpFeyzq1ufxlMr9SqMAI3ziJFSbZN6.Wfj6",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("ReminderManager.Domain.Entities.VibrationSensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AccelerationX")
                        .HasColumnType("double")
                        .HasColumnName("acceleration_x");

                    b.Property<double>("AccelerationZ")
                        .HasColumnType("double")
                        .HasColumnName("acceleration_z");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<double>("Temperature")
                        .HasColumnType("double")
                        .HasColumnName("temperature");

                    b.Property<double>("VelocityX")
                        .HasColumnType("double")
                        .HasColumnName("velocity_x");

                    b.Property<double>("VelocityZ")
                        .HasColumnType("double")
                        .HasColumnName("velocity_z");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("vibration_sensor_data");
                });

            modelBuilder.Entity("ReminderManager.Domain.Entities.VibrationSensorData", b =>
                {
                    b.HasOne("ReminderManager.Domain.Entities.ModbusDeviceConfig", "Device")
                        .WithMany("VibrationSensorDataList")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ReminderManager.Domain.Entities.ModbusDeviceConfig", b =>
                {
                    b.Navigation("VibrationSensorDataList");
                });
#pragma warning restore 612, 618
        }
    }
}
