// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReminderManager.Infrastructure.Data;

#nullable disable

namespace ReminderManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110060147_UpdateModbusTable")]
    partial class UpdateModbusTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReminderManager.Domain.Entities.EmailSender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("EmailSender");
                });

            modelBuilder.Entity("ReminderManager.Domain.Entities.ModbusDeviceConfig", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<bool>("AutoReconnect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_reconnect");

                    b.Property<int>("ConnectionTimeoutMs")
                        .HasColumnType("int")
                        .HasColumnName("connection_timeout_ms");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<int>("ReadIntervalMs")
                        .HasColumnType("int")
                        .HasColumnName("read_interval_ms");

                    b.Property<int>("ReadTimeoutMs")
                        .HasColumnType("int")
                        .HasColumnName("read_timeout_ms");

                    b.Property<int>("ReconnectDelayMs")
                        .HasColumnType("int")
                        .HasColumnName("reconnect_delay_ms");

                    b.Property<ushort>("RegisterCount")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("register_count");

                    b.Property<byte>("SlaveId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("slave_id");

                    b.Property<ushort>("StartAddress")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("start_address");

                    b.HasKey("DeviceId");

                    b.ToTable("ModbusDeviceConfig");
                });

            modelBuilder.Entity("ReminderManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b7ddba6-a1b1-4309-b0aa-5d2dfecc305a"),
                            Password = "$2a$11$/wGOszXI1amy5rII2IN5YerD/iOlFPXXd87qh9eenBOdGm1Oo3tNO",
                            Username = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
